env:
  browser: true
  es2021: true

plugins:
  - react
  - '@stylistic'

extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

rules:
  '@stylistic/semi': ['error', 'never']
  '@stylistic/quotes': ['error', 'single']
  '@stylistic/indent': ['error', 2]
  '@stylistic/comma-dangle': ['error', 'always-multiline']
  '@stylistic/arrow-parens': ['error', 'always']
  '@stylistic/object-curly-spacing': ['error', 'always']
  '@stylistic/brace-style': ['error', 'stroustrup', { 'allowSingleLine': false }]

  no-unused-vars: error

  import/extensions: 0
  import/no-unresolved: 0
  react/prop-types: 0
  no-console: 0
  react/react-in-jsx-scope: 0
  react/function-component-definition:
    - 2
    - namedComponents: 'arrow-function'
  react/jsx-filename-extension:
    - 1
    - extensions:
        - '.js'
        - '.jsx'
